loadTest:
    name: Load Testing
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: '24' # CORRECCIÓN: Actualizado a 24 para evitar el warning

      - name: Install Dependencies
        run: |
          npm install -g artillery
          npm install --save-dev artillery-plugin-ensure
          npm install -g wait-on

      # NUEVO PASO: Iniciar sesión en Docker antes de intentar descargar la imagen
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run container
        run: |
          # Como ya iniciaste sesión arriba, este comando ahora podrá descargar la imagen sin error
          docker run -d --name rest-api -p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          npx wait-on http://localhost:3000 

      - name: Run Load Test
        run: |
          set -e  
          artillery run loadTest/basic.yaml || exit 1